source "/usr/share/fzf/key-bindings.zsh"
source "/usr/share/fzf/completion.zsh"
source "$HOME/dotfiles/shell/plugins/forgit/forgit.plugin.zsh"
source "$HOME/dotfiles/shell/plugins/fzf-tab/fzf-tab.plugin.zsh"
source "$HOME/dotfiles/shell/fzf.zsh"
source "$HOME/dotfiles/shell/git.zsh"
source "$HOME/dotfiles/shell/aliases.zsh"
source "$HOME/dotfiles/shell/functions.zsh"

PATH="$HOME/.cargo/bin:$HOME/.local/bin:$HOME/scripts/:$HOME/dotfiles/shell/plugins/fzf-zsh-plugin/bin:$HOME/.luarocks/bin:${PATH}"
export PATH

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DOWNLOAD_DIR="$HOME/dl"

export MANPAGER="sh -c 'col -bx | bat -l man -p'"

. "$HOME/.cargo/env"
