bindkey -v
export KEYTIMEOUT=1
# echo '\e[5 q'

function precmd {
    print -Pn "\e[ q"
}

autoload -U colors && colors
HISTSIZE=3000
SAVEHIST=3000
HISTFILE=~/.cache/zsh/history

export STARSHIP_CONFIG=~/.config/starship/starship.toml
eval "$(starship init zsh)"
autoload -U compinit && compinit -u

eval "$(zoxide init zsh)"
# cheat.sh zsh completion
fpath=(~/dotfiles/shell/.zsh.d/ $fpath)

eval "$(luarocks path --lua-version 5.1)"

# autostart zellij on shell creation
# eval "$(zellij setup --generate-auto-start zsh)"

# pnpm
export PNPM_HOME="/home/chokerman/.local/share/pnpm"
export PATH="$PNPM_HOME:$PATH"
# pnpm end

export PATH="$PATH:/home/chokerman/.bin"
