bindkey -v
export KEYTIMEOUT=1

function precmd {
    print -Pn "\e[ q"
}

autoload -U colors && colors
HISTSIZE=3000
SAVEHIST=3000
test -d ~/.cache/zsh || mkdir -p ~/.cache/zsh
test -f ~/.cache/zsh/history || touch ~/.cache/zsh/history
HISTFILE=~/.cache/zsh/history

# starship stuff
export STARSHIP_CONFIG=~/.config/starship/starship.toml
eval "$(starship init zsh)"

autoload -U compinit && compinit -u

eval "$(zoxide init zsh)"
# cheat.sh zsh completion
fpath=(~/dotfiles/shell/.zsh.d/ $fpath)

eval "$(luarocks path --lua-version 5.1)"

# autostart zellij on shell creation
# eval "$(zellij setup --generate-auto-start zsh)"

# pnpm
export PNPM_HOME="$HOME/.local/share/pnpm"
export PATH="$PNPM_HOME:$PATH"
