#!/bin/sh
INPUT=$(rofi -dmenu -p "" -theme ~/dotfiles/rofi/styles/prompt.rasi)
[ -z "$INPUT" ] && exit 1

zenity --progress --text="Waiting for an answer" --pulsate &
[ $? -eq 1 ] && exit 1

PID=$!
ANSWER=$(sgpt "$INPUT" --no-animation --no-spinner)
kill $PID
zenity --info --text="$ANSWER"
