#!/bin/sh
input=$(rofi -dmenu -p "  " -mesg "Enter an input for GPT" -theme ~/.config/rofi/styles/prompt.rasi)
[ -z "$input" ] && exit 1

zenity --progress --text="Waiting for an answer" --pulsate &

[ $? -eq 1 ] && exit 1

PID=$!

answer=$(curl -s "https://chatbot.theb.ai/api/chat-process" -H "content-type: application/json" -A "uwu" --data-raw "{\"prompt\":\"$input\",\"options\":{}}" |
    tail -1 | jq -r '.text')

kill $PID
zenity --info --text="$answer"
