#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &

bspc monitor -d I II III IV V VI VII
bspc config focused_border_color "#8C7868"
bspc config normal_border_color "#2B2B2B"
bspc config active_border_color "#cc241d"

bspc config border_width         4
bspc config window_gap           10
bspc config pointer_modifier mod4

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      true

bspc rule -a Screenkey manage=off

picom -f --experimental-backends -b
setxkbmap -option caps:escape,shift:both_capslock &
xrandr --output DP-1 --mode 2560x1440 --rate 165.00--set TearFree on
feh --bg-scale ~/pix/cyberpunk_moon.jpg
xset r rate 300 50
polybar &
dunst
