#!/bin/sh
export SDL_VIDEODRIVER=wayland
export _JAVA_AWT_WM_NONREPARENTING=1

export XDG_CURRENT_DESKTOP=hyprland
export XDG_SESSION_DESKTOP=hyprland
export XDG_CURRENT_SESSION_TYPE=wayland

export GDK_BACKEND="wayland,x11"
export MOZ_ENABLE_WAYLAND=1

export QT_PLUGIN_PATH=/usr/lib/qt/plugins/
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export QT_QPA_PLATFORM=wayland;xcb
export QT_QPA_PLATFORMTHEME=qt5ct 

export GBM_BACKEND=nvidia-drm
export __GLX_VENDOR_LIBRARY_NAME=nvidia
export LIBVA_DRIVER_NAME=nvidia
export __GL_SYNC_DISPLAY_DEVICE=eDP-1

exec Hyprland
#exec river
