return {
  actions = {
    buffer_close = "",
    paste = "",
    search = "",
    tab_close = "",
  },
  git = {
    git = "",
    added = "",
    branch = "",
    changed = "",
    conflict = "",
    deleted = "",
    ignored = "◌",
    renamed = "➜",
    staged = "✓",
    unstaged = "✗",
    untracked = "★",
  },
  lsp_ts = {
    active_lsp = "",
    active_ts = "",
    lsp_loaded = "",
    lsp_loading1 = "",
    lsp_loading2 = "",
    lsp_loading3 = "",
  },
  dap = {
    breakpoint = "",
    breakpoint_condition = "",
    breakpoint_rejected = "",
    logpoint = ".>",
    stopped = "",
  },
  states = {
    file_modified = "",
    file_read_only = "",
    fold_closed = "",
    fold_opened = "",
    fold_separator = " ",
    folder_closed = "",
    folder_empty = "",
    folder_open = "",
    macro_recording = "",
    selected = "❯",
    spellcheck = "暈",
  },
  diagnostics = {
    diagnostic = "裂",
    error = "",
    hint = "",
    info = "",
    warn = "",
  },
  misc = {
    default_file = "",
    ellipsis = "…",
    arrow_left = "",
    arrow_right = "",
    file_modified = "",
    folder_closed = "",
    folder_empty = "",
    selected = "❯",
    spellcheck = "暈",
    v_border = "▐",
  },
}
