[helpers]
color_rgb = ".dotter/helpers/color_rgb.rhai"

[default-applications]
[default-applications.files]
"mimeapps.list" = "~/.config/mimeapps.list"

[wayland]
[wayland.files]
"hyprland/hypr" = "~/.config/hypr/"
# "hyprland/bar/waybar" = "~/.config/waybar/"
"hyprland/bar/eww" = "~/.config/eww/"

[wayland-laptop]
[wayland-laptop.files]
"hyprland/laptop/hypr-laptop" = "~/.config/hypr/"
"hyprland/bar/eww" = "~/.config/eww/"

[alacritty.files]
"terminals/alacritty" = "~/.config/alacritty/"
[foot.files]
"terminals/foot" = "~/.config/foot/"
[wezterm.files]
"terminals/wezterm" = "~/.config/wezterm/"
[zellij.files]
"terminal-tools/zellij" = "~/.config/zellij"

[shell.files]
"shell/zshrc" = "~/.zshrc"
"shell/zshenv" = "~/.zshenv"

[scripts.files]
"scripts" = "~/scripts/"

[starship.files]
"shell/starship" = "~/.config/starship"

[nvim.files]
"coding/neovim/nvim" = "~/.config/nvim/"
[nyoom.files]
"coding/neovim/nyoom/config.fnl" = "~/.config/nyoom/fnl/config.fnl"
"coding/neovim/nyoom/modules.fnl" = "~/.config/nyoom/fnl/modules.fnl"
"coding/neovim/nyoom/packages.fnl" = "~/.config/nyoom/fnl/packages.fnl"
[nvchad.files]
"coding/neovim/nvchad" = "~/.config/nvchad/"
[vscode.files]
"coding/vscode/settings.json" = "~/.config/Code/User/settings.json"
"coding/vscode/keybindings.json" = "~/.config/Code/User/keybindings.json"

[bat.files]
"terminal-tools/bat" = "~/.config/bat/"
[lazygit.files]
"git/lazygit" = "~/.config/lazygit/"
[gh.files]
"git/gh" = "~/.config/gh/"

[mpd.files]
"media/music/mpd" = "~/.config/mpd/"
[mpdris2.files]
"media/music/mpDris2" = "~/.config/mpDris2/"
[ncmpcpp.files]
"media/music/ncmpcpp" = { target = "~/.config/ncmpcpp/", type = "symbolic" }
[spotify-player.files]
"media/music/spotify-player" = "~/.config/spotify-player"

[mpv.files]
"media/mpv" = "~/.config/mpv/"
"media/mpv/input.conf" = "~/.config/mpv/input.conf"
"media/mpv/mpv.conf" = "~/.config/mpv/mpv.conf"
"media/mpv/scripts" = "~/.config/mpv/scripts/"
"media/mpv/script-opts" = "~/.config/mpv/script-opts/"

[zathura.files]
"media/zathura" = "~/.config/zathura/"

[jerry.files]
# "media/jerry" = "~/.config/jerry/"
[lobster.files]
# "media/lobster" = "~/.config/lobster/"


[xplr.files]
"terminal-tools/xplr" = "~/.config/xplr/"

[joshuto.files]
"terminal-tools/joshuto" = "~/.config/joshuto/"

[mimeo.files]
"mimeo" = "~/.config/mimeo/"

[rofi.files]
"launchers/rofi" = "~/.config/rofi/"
[rofi.variables]
rofi_font_size = 14

[mako.files]
"notifications/mako" = { target = "~/.config/mako/", type = "symbolic" }

[fonts.files]
"ui/fonts/" = { target = "~/.local/share/fonts/", type = "symbolic" }

[neofetch.files]
"terminal-tools/neofetch" = "~/.config/neofetch/"
[iamb.files]
"communication/iamb" = { target = "~/.config/iamb/", type = "symbolic" }
[copyq.files]
"clipboard/copyq/copyq.conf" = "~/.config/copyq/copyq.conf"

[multimonitor.variables]
main_monitor = "DP-2"
main_monitor_res = "2560x1440"
main_monitor_refresh = "165.00"
second_monitor = "HDMI-A-1"
second_monitor_res = "1920x1080"
second_monitor_refresh = "144.00"

[graphics.variables.colors16]
base00 = "161616"
base01 = "262626"
base02 = "393939"
base03 = "525252"
base04 = "dde1e6"
base05 = "f2f4f8"
base06 = "ffffff"
base07 = "08bdba"
base08 = "3ddbd9"
base09 = "78a9ff"
base0A = "ee5396"
base0B = "33b1ff"
base0C = "ff7eb6"
base0D = "42be65"
base0E = "be95ff"
base0F = "82cfff"

[catppuccin]
[catppuccin.variables]
theme-name = "catppuccin-mocha"
rofi-wallpaper = "~/dotfiles/wallpapers/images/night.jpg"
[catppuccin.variables.colors16]
base00 = "1e1e2e"
base01 = "181825"
base02 = "313244"
base03 = "45475a"
base04 = "585b70"
base05 = "cdd6f4"
base06 = "f5e0dc"
base07 = "b4befe"
base08 = "f38ba8"
base09 = "fab387"
base0A = "f9e2af"
base0B = "a6e3a1"
base0C = "94e2d5"
base0D = "89b4fa"
base0E = "cba6f7"
base0F = "f2cdcd"

[graphics.variables.font]
family = "Liga SFMono Nerd Font"
size = 14
size_small = 12
huge = 30

[graphics.variables.pictures]
profile = "$HOME/dotfiles/pictures/lain-oxocarbon-transparent.png"
black = "$HOME/dotfiles/pictures/lain-oxocarbon-black.png"
