#!/bin/sh

get_cover() {
    song_path=$(playerctl metadata xesam:url | sed -nE "s@file://(/home/.*)(.*)@\1/music\2@p")
    ffmpegthumbnailer -i "$song_path" -o /tmp/currently-playing.jpg -s0
}

case "$1" in
    get_cover)
        get_cover
        ;;
esac
