#!/bin/sh

status=$(nmcli g | grep -oE "disconnected")
essid=$(nmcli -t -f active,ssid dev wifi | sed -nE "s@yes:(.*)@\1@p")

if [ $status ]; then
    icon="睊"
    text=""
    col="#575268"
else
    icon=""
    text="${essid}"
    col="#a1bdce"
fi

case $1 in
--COL) echo $col ;;
--ESSID) echo "$text" ;;
--ICON) echo $icon ;;
esac
